version: "3"

services:
    web:
        build: .
        #image: localhost:2005/md-file-viewer:latest
        ports:
            - "6060:8080"
        volumes:
            - /docker/markdrive:/Documents:ro
        restart: "unless-stopped"
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "128M"
                reservations:
                    cpus: "0.1"
                    memory: "32M"
