version: "3"

services:
    web:
        #build: .
        image: md-file-viewer:latest
        ports:
            - "2000:8080"
        restart: "unless-stopped"
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: "128M"
                reservations:
                    cpus: "0.1"
                    memory: "32M"
